# NUMPY CRASH COURSE

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# CREATING ARRAY

In [6]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

In [8]:
my_list=(0,1,2,3,4,5)
my_list

(0, 1, 2, 3, 4, 5)

In [9]:
type(my_list)

tuple

In [10]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
type(arr)

numpy.ndarray

In [12]:
type(my_list)

tuple

#### np.arange()

In [113]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [115]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [117]:
np.arange(3,0)#stop is 0 or start is greater than stop.

array([], dtype=int32)

In [119]:
np.arange(3.0)

array([0., 1., 2.])

In [121]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [123]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [125]:
np.arange(20,10)#1st arg shopuld less than 2nd arg

array([], dtype=int32)

In [127]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [129]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [131]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [133]:
np.arange(-20,-30)# cause 1st arg > 2nd arg

array([], dtype=int32)

In [135]:
np.arange(30,20)

array([], dtype=int32)

In [137]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [139]:
np.arange(10,10)

array([], dtype=int32)

In [141]:
np.arange()#cause stop is not given.

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(,10)

In [ ]:
np.arange(10,30,5)

In [ ]:
np.arange(0,10,3)

In [ ]:
np.arange(10,30,5,8)#only start,stop & step allowed or not more than 3 arg.

#### np.zeros(2,3)
>bydefault 1st arg is raw & 2nd arg is column

In [147]:
np.zeros(3) #parameter tunning

array([0., 0., 0.])

In [149]:
np.zeros(-3)

ValueError: negative dimensions are not allowed

In [151]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [153]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [155]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [157]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [159]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [161]:
zero=np.zeros([2,2])
print(zero)

print('###')

print(type(zero))

[[0. 0.]
 [0. 0.]]
###
<class 'numpy.ndarray'>


In [163]:
zero=np.zeros((2,10))
print(zero)
print("###")
print(type(zero))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
###
<class 'numpy.ndarray'>


In [165]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [167]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [169]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [171]:
n= (6,7)
n1=(6,8)
print(np.zeros(n1)) #parameter tunning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [173]:
print(np.zeros(n,dtype=int)) #hyperparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [175]:
n

(6, 7)

In [177]:
n1

(6, 8)

In [179]:
print(np.zeros(n))
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### np.ones(3)

In [182]:
np.ones(3)

array([1., 1., 1.])

In [184]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [186]:
np.ones((2,2),dtype=int)#Bydefault 1st will give raw and 2nd is column

array([[1, 1],
       [1, 1]])

In [188]:
n

(6, 7)

In [190]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [192]:
np.twos([2,2])

AttributeError: module 'numpy' has no attribute 'twos'

In [194]:
np.three((2,3))

AttributeError: module 'numpy' has no attribute 'three'

In [196]:
np.ones(2)

array([1., 1.])

In [198]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [200]:
np.ones([2,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [202]:
np.ones((3,4),dtype=str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [204]:
np.ones([2,3],dtype=str)


array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [206]:
np.ones([3,4],dtype=bool)


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [208]:
np.ones([3,4],dtype=complex)


array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [210]:
np.ones([6,10],dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [212]:
range(5)

range(0, 5)

In [214]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [216]:
r=range(5)
r

range(0, 5)

In [218]:
for i in r:
    print(i)

0
1
2
3
4


In [220]:
list(range(5))

[0, 1, 2, 3, 4]

In [222]:
tuple(range(5))

(0, 1, 2, 3, 4)

In [224]:
set(range(5))

{0, 1, 2, 3, 4}

In [226]:
dict(range(5))

TypeError: cannot convert dictionary update sequence element #0 to a sequence

In [228]:
r

range(0, 5)

In [230]:
range(1,10)

range(1, 10)

In [232]:
list(range(1,10,3))

[1, 4, 7]

In [234]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [236]:
type(y)

list

In [238]:
y=np.array(y)

In [240]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### np.random.randa()

In [243]:
rand(3,2)

NameError: name 'rand' is not defined

In [245]:
random.rand(3,3)

NameError: name 'random' is not defined

In [247]:
np.random.rand(5)

array([0.27868982, 0.45065528, 0.06088688, 0.81029421, 0.00287715])

In [249]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [251]:
np.random(2)

TypeError: 'module' object is not callable

In [253]:
np.random.rand(2,4)#provide unique number each time

array([[0.75903972, 0.85860151, 0.86309741, 0.33787441],
       [0.43811179, 0.58369654, 0.60263967, 0.3893825 ]])

### np.random.randit()

In [256]:
np.random.randint(4)# 4 is exclusive

0

In [258]:
np.random.randint(2,6)#2nd arg is exclusive

2

In [260]:
np.random.randint(0,1)

0

In [262]:
np.random.randint(10,20,4)#by running each time its value change but not more than or print 20.

array([19, 16, 19, 10])

In [264]:
np.random.randint(1,10,4)

array([4, 7, 3, 1])

In [266]:

np.random.randint(1,6,4)

array([4, 2, 4, 2])

In [268]:
np.random.rand(3)

array([0.71871555, 0.61390022, 0.15306826])

In [270]:
np.random.randint(1)

0

In [272]:
np.random.randint(30,20,10)#cause 1st>2nd

ValueError: low >= high

In [274]:
np.random.randint(20,30,10)#ist arg should less than 2nd arg


array([27, 21, 22, 20, 22, 21, 26, 27, 24, 24])

In [276]:
np.random.randint(5,9)

8

In [278]:
np.random.randint(10,21,3)

array([12, 19, 15])

In [280]:
np.random.randint(1,12,10)

array([ 9, 11,  3,  1, 11,  4, 10,  1,  7,  5])

In [282]:
np.random.randint(10,40,(10,10))#10 row,10 column

array([[16, 14, 11, 30, 15, 22, 11, 24, 24, 27],
       [25, 30, 38, 12, 15, 34, 32, 12, 16, 39],
       [23, 21, 15, 31, 16, 13, 30, 29, 39, 31],
       [23, 25, 28, 16, 32, 13, 34, 28, 33, 23],
       [29, 27, 23, 37, 39, 28, 10, 23, 14, 27],
       [13, 15, 26, 27, 17, 31, 12, 32, 31, 14],
       [31, 27, 18, 28, 39, 14, 39, 12, 15, 34],
       [10, 32, 26, 12, 28, 24, 13, 39, 34, 38],
       [29, 30, 30, 36, 18, 11, 35, 29, 34, 31],
       [28, 31, 29, 13, 17, 17, 22, 35, 21, 30]])

In [284]:
np.random.randint(1,10,[2,4])

array([[8, 6, 9, 7],
       [7, 2, 6, 1]])

In [286]:
np.random.randint(1,100,(12,12))

array([[42, 26, 78, 99, 22, 45, 42, 37, 31, 70, 54, 65],
       [ 7, 68, 44, 47, 79, 36, 31, 41, 29,  6, 31, 50],
       [69, 50, 89, 57, 23, 94, 93,  4, 92, 68, 95, 31],
       [25, 19, 54, 33, 15, 85, 12,  2, 20, 23, 73,  5],
       [ 6, 92, 12,  7, 35, 62, 82, 81, 34, 70, 32, 84],
       [65, 82, 22, 32, 83, 61, 74, 41, 17, 65, 27, 74],
       [90, 18, 40,  7, 88, 95, 60, 99, 51, 25, 52, 76],
       [24, 90, 99, 91, 82, 97, 89, 16, 13, 58, 88, 35],
       [59, 51, 78, 43, 68, 40,  6, 62, 98, 87, 19, 50],
       [ 8, 61, 59, 59, 20, 59, 35, 26, 24, 87,  5, 98],
       [83,  3, 89, 89, 68, 45, 77, 49,  4, 73, 85, 71],
       [21, 84, 37, 60, 97, 78, 12, 22, 20, 96, 99, 78]])

### np.arange().reshape()

In [289]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [291]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [293]:
np.arange(20,100).reshape(1,80)

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [295]:
np.arange(31,90).reshape(1,59)

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
        47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
        63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
        79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [297]:
b=np.random.randint(10,20,(5,4))

In [299]:
b

array([[14, 15, 16, 15],
       [11, 12, 11, 14],
       [10, 15, 11, 12],
       [14, 14, 14, 14],
       [18, 11, 16, 16]])

In [301]:
type(b)

numpy.ndarray

In [303]:
b

array([[14, 15, 16, 15],
       [11, 12, 11, 14],
       [10, 15, 11, 12],
       [14, 14, 14, 14],
       [18, 11, 16, 16]])

In [305]:
b[:]

array([[14, 15, 16, 15],
       [11, 12, 11, 14],
       [10, 15, 11, 12],
       [14, 14, 14, 14],
       [18, 11, 16, 16]])

In [307]:
b[1:3]

array([[11, 12, 11, 14],
       [10, 15, 11, 12]])

In [309]:
b

array([[14, 15, 16, 15],
       [11, 12, 11, 14],
       [10, 15, 11, 12],
       [14, 14, 14, 14],
       [18, 11, 16, 16]])

In [311]:
b[1,2]#intersection point of 1 row & 2 column or simp 1 raw's 3rd elem.

11

In [313]:
b[1,-1]

14

In [315]:
b[2,-2]

11

In [317]:
b[-3,3]

12

In [319]:
b

array([[14, 15, 16, 15],
       [11, 12, 11, 14],
       [10, 15, 11, 12],
       [14, 14, 14, 14],
       [18, 11, 16, 16]])

In [321]:
b[3:6]

array([[14, 14, 14, 14],
       [18, 11, 16, 16]])

In [323]:
c=np.random.randint(1,20,(7,7))


In [325]:
c

array([[ 1,  1, 10,  4,  1, 12,  1],
       [ 7, 14,  7, 14, 10, 12,  9],
       [17,  3,  5,  6,  5, 17, 12],
       [13, 13,  4, 13,  2,  9, 15],
       [13,  2,  1, 15,  2, 12, 11],
       [ 7, 17,  6,  4, 14, 15, 10],
       [ 5, 18, 17,  8,  4, 17, 10]])

In [327]:
c[3:7]#cosider rows for array slicing-from 3 row to 6 row// idx start from 0

array([[13, 13,  4, 13,  2,  9, 15],
       [13,  2,  1, 15,  2, 12, 11],
       [ 7, 17,  6,  4, 14, 15, 10],
       [ 5, 18, 17,  8,  4, 17, 10]])

In [329]:
c[0:-1]

array([[ 1,  1, 10,  4,  1, 12,  1],
       [ 7, 14,  7, 14, 10, 12,  9],
       [17,  3,  5,  6,  5, 17, 12],
       [13, 13,  4, 13,  2,  9, 15],
       [13,  2,  1, 15,  2, 12, 11],
       [ 7, 17,  6,  4, 14, 15, 10]])

In [331]:
c[-1:0]# by default, Python slices forward, 
#so when the start index is greater than the stop index, and no negative step is given,
#you get an empty result.

array([], shape=(0, 7), dtype=int32)

In [333]:
c

array([[ 1,  1, 10,  4,  1, 12,  1],
       [ 7, 14,  7, 14, 10, 12,  9],
       [17,  3,  5,  6,  5, 17, 12],
       [13, 13,  4, 13,  2,  9, 15],
       [13,  2,  1, 15,  2, 12, 11],
       [ 7, 17,  6,  4, 14, 15, 10],
       [ 5, 18, 17,  8,  4, 17, 10]])

In [335]:
c[-4,2]

4

In [337]:
np.random.randint(10,20,(4,4))

array([[16, 19, 16, 13],
       [19, 10, 10, 17],
       [17, 19, 10, 11],
       [12, 17, 15, 11]])

In [339]:
b

array([[14, 15, 16, 15],
       [11, 12, 11, 14],
       [10, 15, 11, 12],
       [14, 14, 14, 14],
       [18, 11, 16, 16]])

In [341]:
b[-4:-2]#Because -4:-2 → means rows 1 and 2 (in positive index terms).



array([[11, 12, 11, 14],
       [10, 15, 11, 12]])

In [343]:
c

array([[ 1,  1, 10,  4,  1, 12,  1],
       [ 7, 14,  7, 14, 10, 12,  9],
       [17,  3,  5,  6,  5, 17, 12],
       [13, 13,  4, 13,  2,  9, 15],
       [13,  2,  1, 15,  2, 12, 11],
       [ 7, 17,  6,  4, 14, 15, 10],
       [ 5, 18, 17,  8,  4, 17, 10]])

In [345]:
print(len(b))
print(len(c))

5
7


In [347]:
c[-3:-2]

array([[13,  2,  1, 15,  2, 12, 11]])

In [349]:
c[-1:-4]#cause 1st arg > 2nd arg

array([], shape=(0, 7), dtype=int32)

### OPERATION

In [352]:
a=np.random.randint(10,20,10)#3rd arg is size of elem

In [354]:
a

array([19, 17, 14, 11, 14, 17, 19, 13, 16, 18])

In [356]:
id(a)

2286856848272

In [358]:
arr

array([0, 1, 2, 3, 4, 5])

In [360]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[43, 11,  6, 33, 28, 25, 84, 80,  4, 44],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14],
       [28,  4, 73, 93, 64, 75, 31,  5, 57, 42],
       [63, 68, 73,  0, 35, 46, 66, 69, 36, 82],
       [88,  5,  1, 19, 96, 76, 84, 13, 45, 84]])

In [362]:
np.arange(1,100).reshape(9,11)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66],
       [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77],
       [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
       [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [364]:
arr2

array([[43, 11,  6, 33, 28, 25, 84, 80,  4, 44],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14],
       [28,  4, 73, 93, 64, 75, 31,  5, 57, 42],
       [63, 68, 73,  0, 35, 46, 66, 69, 36, 82],
       [88,  5,  1, 19, 96, 76, 84, 13, 45, 84]])

In [366]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [368]:
arr

array([0, 1, 2, 3, 4, 5])

In [370]:
arr[:4]

array([0, 1, 2, 3])

In [372]:
arr2[:]

array([[43, 11,  6, 33, 28, 25, 84, 80,  4, 44],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14],
       [28,  4, 73, 93, 64, 75, 31,  5, 57, 42],
       [63, 68, 73,  0, 35, 46, 66, 69, 36, 82],
       [88,  5,  1, 19, 96, 76, 84, 13, 45, 84]])

In [374]:
arr2[0:5]

array([[43, 11,  6, 33, 28, 25, 84, 80,  4, 44],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73]])

In [376]:
arr2[1:4]

array([[17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4]])

In [378]:
arr2

array([[43, 11,  6, 33, 28, 25, 84, 80,  4, 44],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14],
       [28,  4, 73, 93, 64, 75, 31,  5, 57, 42],
       [63, 68, 73,  0, 35, 46, 66, 69, 36, 82],
       [88,  5,  1, 19, 96, 76, 84, 13, 45, 84]])

In [380]:
arr2[-5,-3]

13

In [382]:
arr2

array([[43, 11,  6, 33, 28, 25, 84, 80,  4, 44],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14],
       [28,  4, 73, 93, 64, 75, 31,  5, 57, 42],
       [63, 68, 73,  0, 35, 46, 66, 69, 36, 82],
       [88,  5,  1, 19, 96, 76, 84, 13, 45, 84]])

In [384]:
len(arr2)

10

In [386]:
arr2[-5,-5]

66

In [388]:
arr2[::-1]

array([[88,  5,  1, 19, 96, 76, 84, 13, 45, 84],
       [63, 68, 73,  0, 35, 46, 66, 69, 36, 82],
       [28,  4, 73, 93, 64, 75, 31,  5, 57, 42],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [43, 11,  6, 33, 28, 25, 84, 80,  4, 44]])

In [390]:
arr2[::1]


array([[43, 11,  6, 33, 28, 25, 84, 80,  4, 44],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14],
       [28,  4, 73, 93, 64, 75, 31,  5, 57, 42],
       [63, 68, 73,  0, 35, 46, 66, 69, 36, 82],
       [88,  5,  1, 19, 96, 76, 84, 13, 45, 84]])

In [392]:
arr2[::]


array([[43, 11,  6, 33, 28, 25, 84, 80,  4, 44],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14],
       [28,  4, 73, 93, 64, 75, 31,  5, 57, 42],
       [63, 68, 73,  0, 35, 46, 66, 69, 36, 82],
       [88,  5,  1, 19, 96, 76, 84, 13, 45, 84]])

In [394]:
arr2[::-2]


array([[88,  5,  1, 19, 96, 76, 84, 13, 45, 84],
       [28,  4, 73, 93, 64, 75, 31,  5, 57, 42],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15]])

In [396]:
arr2[::-3]


array([[88,  5,  1, 19, 96, 76, 84, 13, 45, 84],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [43, 11,  6, 33, 28, 25, 84, 80,  4, 44]])

In [398]:
arr2[1:4:-1]


array([], shape=(0, 10), dtype=int32)

In [400]:
arr2

array([[43, 11,  6, 33, 28, 25, 84, 80,  4, 44],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14],
       [28,  4, 73, 93, 64, 75, 31,  5, 57, 42],
       [63, 68, 73,  0, 35, 46, 66, 69, 36, 82],
       [88,  5,  1, 19, 96, 76, 84, 13, 45, 84]])

In [402]:
arr2[:-3]

array([[43, 11,  6, 33, 28, 25, 84, 80,  4, 44],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14]])

In [404]:
arr

array([0, 1, 2, 3, 4, 5])

In [406]:
arr.max()

5

In [408]:
arr.min()

0

In [410]:
arr2.max()

98

In [412]:
arr2.min()

0

In [414]:
arr.sum()

15

In [416]:
arr2.sum()

5304

In [418]:
                    #Sum of all values
arr2.mean()# Mean= ----------------------------
                  #Total number of values



53.04

In [420]:
rows, cols = b.shape


In [422]:
print("no of rows",arr2.shape[0])#calculation for row amd column.
print("no of columns",arr2.shape[1])


no of rows 10
no of columns 10


In [424]:
arr2.shape[1]#no of column

10

In [426]:
arr2.shape[0]#no of row


10

In [428]:
arr2.size#sum of the element

100

In [430]:
arr.shape

(6,)

In [432]:
arr2.shape#no of row & column

(10, 10)

In [434]:
arr2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [436]:
arr2.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [438]:
from numpy import *
arr2=array(arr2)
median(arr2)

57.0

In [440]:
from numpy import *
arr=array(arr)
median(arr)

2.5

In [442]:
median=np.median(arr2)
median

57.0

In [444]:
mean=np.mean(arr2)
mean

53.04

In [450]:
arr

array([0, 1, 2, 3, 4, 5])

In [452]:
arr2

array([[43, 11,  6, 33, 28, 25, 84, 80,  4, 44],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14],
       [28,  4, 73, 93, 64, 75, 31,  5, 57, 42],
       [63, 68, 73,  0, 35, 46, 66, 69, 36, 82],
       [88,  5,  1, 19, 96, 76, 84, 13, 45, 84]])

In [454]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [456]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [458]:
arr

array([0, 1, 2, 3, 4, 5])

In [462]:
arr.reshape(2,3,order='C')#row major (default)

array([[0, 1, 2],
       [3, 4, 5]])

In [487]:
arr2.reshape(10,10,order='F')#column major #print element with fortran

array([[43, 11,  6, 33, 28, 25, 84, 80,  4, 44],
       [17, 86, 92, 62,  4, 97, 82, 28, 63, 15],
       [65, 77, 69, 50, 37,  6, 83, 50, 98, 94],
       [51, 37, 60,  0, 75, 91, 98, 34, 81,  4],
       [52, 70, 89, 57, 52, 63, 89, 70, 55, 73],
       [88, 74, 63, 54,  9, 66, 44, 13, 26, 91],
       [47,  3, 51, 71, 96, 14, 41, 94, 90, 14],
       [28,  4, 73, 93, 64, 75, 31,  5, 57, 42],
       [63, 68, 73,  0, 35, 46, 66, 69, 36, 82],
       [88,  5,  1, 19, 96, 76, 84, 13, 45, 84]])

In [479]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [489]:
arr.reshape(2,3,order="A") # A almost give you c type output

array([[0, 1, 2],
       [3, 4, 5]])

In [491]:
arr

array([0, 1, 2, 3, 4, 5])

In [493]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [495]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [497]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [499]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [501]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

## INDEXING

In [506]:
mat= np.arange(0,100).reshape(10,10)

In [508]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [510]:
row=4
col=5

In [512]:
row

4

In [514]:
col

5

In [516]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [520]:
mat[row,col]

45

In [522]:
mat[4,5]

45

In [524]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [526]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [528]:
col=6

In [530]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [532]:
mat[6]#bydefault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [534]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [538]:
#with slicing
mat[:,col]#select the col,that is 6th colun

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [540]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [542]:
mat[row,:] #select the row,that is 4th row


array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [544]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [546]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [548]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [550]:
mat[:col]#0:6

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [552]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [554]:
row

4

In [558]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [560]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [564]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [566]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [568]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [574]:
mat[,3]

SyntaxError: invalid syntax (2688842439.py, line 1)

In [576]:
mat[1,3]


13

In [578]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [580]:
row

4

In [582]:
col

6

In [584]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [586]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [588]:
mat[1,4]

14

In [590]:
mat[3,-3]#turn negative indx to positive that means -3 =7 idx or row

37

In [592]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [594]:
mat[0,0]

0

In [596]:
mat[-1:0]

array([], shape=(0, 10), dtype=int32)

In [600]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [598]:
mat[0:-1]3print except -1 row

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [604]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [608]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [610]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [612]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [614]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [616]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [618]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [620]:
mat[:-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [626]:
mat[0:1:-1]

array([], shape=(0, 10), dtype=int32)

In [624]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [628]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [630]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [634]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [632]:
mat[2:6,2:4]#1:5 -> only row part /// 1:3 -- it indicates only column parts 

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [636]:
mat[1:3,2:4]

array([[12, 13],
       [22, 23]])

In [638]:
mat[2:5,3:6]

array([[23, 24, 25],
       [33, 34, 35],
       [43, 44, 45]])

In [640]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [642]:
mat[1:2,2:4]

array([[12, 13]])

In [644]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## MASKING

In [649]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [651]:
id(mat)

2286857114064

In [653]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [655]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [657]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [659]:
mat[mat==50]

array([50])

In [661]:
mat[mat<40]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [663]:
mat < 40

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [665]:
mat==40

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [667]:
mat[mat==40

array([40])

In [669]:
mat > 40

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [671]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [673]:
a1 = mat [mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [675]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [677]:
a2=mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [679]:
a3=mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [681]:
a4=mat[mat==50]
a4

array([50])

## Python program to generat otp

In [694]:
import random

def generate_otp(length=4):
    """Genrate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

#example usage
otp_length = 4 # you can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is : {otp}")

Your OTP is : 5323


In [698]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [700]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [702]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x0000021473C2AD40>


In [704]:
x=[1,2,3]
y=x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
